#################################################################################
# Copyright (c) 2024, 2025 T-Systems International GmbH
# Copyright (c) 2024, 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

openapi: 3.0.0
info:
  version: TagusRelease
  title: SD-Factory API
  description: API for creating and storing the Verifiable Credentials
paths:
  /api/tagus/selfdescription:
    post:
      summary: Creates a Verifiable Credential and returns it
      operationId: selfdescriptionPost
      requestBody:
        required: true
        description: parameters to generate VC
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LegalParticipantSchema'
                - $ref: '#/components/schemas/ServiceOfferingSchema'
              discriminator:
                propertyName: type
                mapping:
                  LegalParticipant: '#/components/schemas/LegalParticipantSchema'
                  ServiceOffering: '#/components/schemas/ServiceOfferingSchema'
            examples:
              LegalParticipant:
                description: payload to create LegalParticipant
                value:
                    externalId: ID01234-123-4321
                    type: LegalParticipant
                    holder: BPNL000000000000
                    name: CAXSDUMMYCATENAZZ
                    registrationNumber:
                      - type: taxID
                        value: o12345678
                    headquarterAddress.countrySubdivisionCode: DE-BY
                    legalAddress.countrySubdivisionCode: DE-NW
              ServiceOffering:
                description: payload to create ServiceOffering
                value:
                  externalId: ID01234-123-4321
                  type: ServiceOffering
                  holder: BPNL000000000000
                  termsAndConditions:
                    gx:URL: https://raw.githubusercontent.com/eclipse-tractusx/sd-factory/main/LICENSE
                    gx:hash: A8789884DECDE0E00D75FA204A78E0A000
                  issuer: CAXSDUMMYCATENAZZ
                  providedBy: https://participant.url
                  policy: https://policy.url
                  aggregationOf: https://aggr1.url, https://aggr2.url
                  dataProtectionRegime:
                    - GDPR2016
                  dataAccountExport:
                    gx:requestType: API
                    gx:accessType: digital
                    gx:formatType: application/json
                  connectorUrl: https://company.connector-url.org/
      responses:
        '202':
          description: request has been accepted for processing
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    SelfDescriptionSchema:
      type: object
      properties:
        type:
          type: string
        holder:
          type: string
        externalId:
          type: string
        attachment:
          type: array
          description: any VC that can be attached to a resource
          items: { }
          minItems: 1
          maxItems: 10
      required:
        - type
        - holder
        - externalId
    RegistrationNumberSchema:
      type: object
      description: Registration Number element
      properties:
        type:
          type: string
          description: the mean to request data retrieval
          enum:
            - taxID
            - vatID
            - EUID
            - EORI
            - leiCode
        value:
          type: string
          description: Registration Number value
          minLength: 1
          maxLength: 128
    LegalParticipantSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - type: object
          properties:
            name:
              type: string
            registrationNumber:
              type: array
              uniqueItems: true
              minItems: 1
              maxItems: 512
              description: A list of registration numbers
              items:
                $ref: '#/components/schemas/RegistrationNumberSchema'
            headquarterAddress.countrySubdivisionCode:
              type: string
            legalAddress.countrySubdivisionCode:
              type: string
          required:
            - registrationNumber
            - headquarterAddress.countrySubdivisionCode
            - legalAddress.countrySubdivisionCode
    ServiceOfferingSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - type: object
          properties:
            aggregationOf:
              type: array
              uniqueItems: true
              minItems: 1
              maximum: 512
              items:
                type: string
                format: uri
            termsAndConditions:
              type: object
              properties:
                gx:URL:
                  type: string
                gx:hash:
                  type: string
            providedBy:
              type: string
              format: uri
            policy:
              type: string
              format: uri
            dataProtectionRegime:
              type: array
              uniqueItems: true
              minItems: 1
              maximum: 10
              items:
                type: string
            dataAccountExport:
              type: object
              properties:
                gx:requestType:
                  type: string
                gx:accessType:
                  type: string
                gx:formatType:
                  type: string
            connectorUrl:
              type: string
              format: uri
          required:
            - providedBy
security:
  - bearerAuth: []
